name: API Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install dependencies
        run: yarn install
        working-directory: ./retro-board-api

      - name: Run tests
        run: yarn run test:nowatch
        working-directory: ./retro-board-api
